Assignments/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignments.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        public int CategoryId { get; set; }

        [Required]
        public string CategoryName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}

Assignments/Controllers/SupervisorController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignments.Models;
using System.Data;
using System.Net;
using System.Data.Entity;
using PagedList;
using Assignments.Interface;

namespace Assignments.Controllers
{
    [Authorize]
    public class SupervisorController : Controller
    {
        private readonly Iinvoice _Iinvoice;
        private readonly IProduct _IProduct;

        public SupervisorController(Iinvoice invoice, IProduct product)
        {
            _Iinvoice = invoice;
            _IProduct = product;
        }

        assignment1Entities2 db = new assignment1Entities2();
        Assignments.Models.Product product = new Models.Product();

        public ActionResult Index(string sortOn, string orderBy, string pSortOn, string keyword, int? page)
        {
            int recordsPerPage = 5;
            if (!page.HasValue)
            {
                page = 1; // set initial page value
                if (string.IsNullOrWhiteSpace(orderBy) || orderBy.Equals("asc"))
                {
                    orderBy = "desc";
                }
                else
                {
                    orderBy = "asc";
                }
            }

            // override the sort order if the previous sort order and current request sort order is different
            if (!string.IsNullOrWhiteSpace(sortOn) && !sortOn.Equals(pSortOn,
StringComparison.CurrentCultureIgnoreCase))
            {
                orderBy = "asc";
            }

            ViewBag.OrderBy = orderBy;
            ViewBag.SortOn = sortOn;
            ViewBag.Keyword = keyword;

            var list = db.Products.AsQueryable();

            switch (sortOn)
            {
                case "ProductName":
                    if (orderBy.Equals("desc"))
                    {
                        list = list.OrderByDescending(p => p.ProductName);
                    }
                    else
                    {
                        list = list.OrderBy(p => p.ProductName);
                    }
                    break;
                case "ProductPrice":
                    if (orderBy.Equals("desc"))
                    {
                        list = list.OrderByDescending(p => p.ProductPrice);
                    }
                    else
                    {
                        list = list.OrderBy(p => p.ProductPrice);
                    }
                    break;
                default:
                    list = list.OrderBy(p => p.ProductId);
                    break;
            }
            if (!string.IsNullOrWhiteSpace(keyword))
            {
                list = list.Where(f => f.ProductName.StartsWith(keyword));
            }
            var finalList = list.ToPagedList(page.Value, recordsPerPage);
            return View(finalList);
        }

        [HttpGet]
        public ActionResult Create()
        {
            product.GetCategory = _IProduct.GetAllCategory();
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, Models.Product product)
        {
            if (ModelState.IsValid)
            {
                int userId = _Iinvoice.GetCurrentUserId();
                product.CreatedBy = userId;
                string result = _IProduct.Create(file, product);
                ViewBag.msg = result;
            }
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = db.Products.Find(id);
            Session["imgPath"] = product.ProductImage;

            var catlist = _IProduct.SelectallCategories();
            ViewBag.catlist = new SelectList(catlist, "CategoryId", "CategoryName", product.CategoryId);

            // if record not found
            if (product == null)
            {
                return HttpNotFound();      // 404 Page display
            }
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase file, Models.Product product)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    int userId = _Iinvoice.GetCurrentUserId();
                    product.CreatedBy = userId;

                    string result = _IProduct.Edit(file, product);
                    ViewBag.msg = result;
                }
                else
                {
                    product.ProductImage = Session["imgPath"].ToString();
                    db.Entry(product).State = EntityState.Modified;
                    product.CategoryId = Convert.ToInt32(product.CategoryName);

                    if (db.SaveChanges() > 0)
                    {
                        TempData["msg"] = "Data Updated";
                        return RedirectToAction("index");
                    }
                }
            }
            return View();
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            string currentImage = Request.MapPath(product.ProductImage);

            db.Entry(product).State = EntityState.Deleted;
            if (db.SaveChanges() > 0)
            {
                if (System.IO.File.Exists(currentImage))
                {
                    System.IO.File.Delete(currentImage);
                }
                TempData["msg"] = "Data Deleted";
                return RedirectToAction("index");
            }
            return View();
            //string result = _IProduct.Delete(id);
            //ViewBag.msg = result;

            //return View("Index");
        }
    }
}

Assignments/Views/Supervisor/Add.cshtml
@model Assignments.Database.Product1

@{
    ViewBag.Title = "Add";
}

<script type="text/javascript">
    $(document).ready(function){
        $("#btnSave").click(function){
            SaveProduct();
        });
    });

    function ResetProduct()
    {
        $("#CategoryId").val();
        $("#ProductName").val();
        $("#Description").val());
        $("#ProductPrice").val());
        $("#ImagePath").get(0).items[0]);
    }

    function SaveProduct(){
        var formData = new FormData;
        formData.append("CategoryId",$("#CategoryId").val());
        formData.append("ProductName",$("#ProductName").val());
        formData.append("Description",$("#Description").val());
        formData.append("ProductPrice",$("#ProductPrice").val());
        formData.append("ImagePath",$("#ImagePath").get(0).items[0]);

        $ajax({
            async: true,
            datatype:'JSON',
            type:'POST',
            contentType: false,
            processorType: false,
            url: '/Supervisor/Add',
            data: formData,
            success:function(data){
                alert(data);
            },
            error:function()
            {
                alert("There is some problem to add Product");
            }
        })
    }
</script>
<div class="container">
    <div class="col-md-4">
        <div class="form-group">
            Category :
            @Html.DropDownListFor(model=>model.CategoryId, new SelectList(Model.CategorySelectListItem,"Value","Text") ,
           new { @class="form-control"})
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            Product Name :
            @Html.TextBoxFor(model=>model.ProductName, new { @class = "form-control" })
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            Description :
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            Product Price :
            @Html.TextBoxFor(model => model.ProductPrice, new { @class = "form-control" })
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            Product Price :
            @Html.TextBoxFor(model => model.ImagePath, new {type="file", @class = "form-control" })
        </div>
    </div>
    <div>
        <input type="button" value="Save" name="save" class="btn btn-primary"/>
        &nbsp;
        <input type="button" value="Reset" name="reset" class="btn btn-danger" />
    </div>
</div>

Assignments/Views/Supervisor/AddNewProduct.cshtml
@model IEnumerable<Assignments.Models.Product>
@{
    ViewBag.Title = "AddNewProduct";
}


<div class="container">
    <h2>Add New Product</h2>
    <div class="row">
        <div class="col-md-6">
            <form id="AddNewProduct" method="post" enctype="multipart/form-data" onsubmit="return AjaxPost(this)">
                <label>Product Name</label>
                <input id="ProductName" name="ProductName" class="form-control" placeholder="Product Name"/>

                <label>Description</label>
                <input id="Description" name="Description" class="form-control" placeholder="Description" />

                <label>Product Name</label>
                <input id="ProductPrice" name="ProductPrice" class="form-control" placeholder="Product Price" />

                <label>Product Name</label>
                <input id="ImageUpload" name="ImageUpload" class="form-control" type="file"/>

                <button class="btn btn-danger">Add</button>
            </form>
        </div>
    </div>
</div>

<br/><br /><br />

<div class="container">
    <h2 class="text-center">Product List</h2>
    @foreach(var item in Model)
    {
        double price = Convert.ToInt32(@item.ProductPrice);

        <div class="col-md-3" style="margin-bottom:25px">
            <div class="thumbnail">
                <div class="image" style="margin-bottom:20px;">
                    <img class="img-responsive" src="~/image/@item.ImagePath" height="350" width="240"/>
                </div>
                <div class="caption" style="border-top:3px solid #808080">
                    <h3><a href="#">@item.ProductName</a></h3>
                    <h4>@price.ToString("F2")Rs.</h4>
                </div>
            </div>
        </div>
    }
</div>

<script>
    function AjaxPost(formData) {
        var ajaxConfig = {
            type: "post",
            url: "/Supervisor/SaveData",
            data: new FormData(formData),
            success: function (result) {
                alert(result);
                window.location.href("/Supervisor/AddNewProduct")
            }
        }
        if($(formData).attr('enctype') =="multipart/form-data")
        {
            ajaxConfig["contentType"] = false;
            ajaxConfig["processData"] = false;
        }
        $.ajax(ajaxConfig);
        return false;
    }
</script>

Assignments/Views/Supervisor/Category.cshtml
@model Assignments.Models.ViewModel

@{
    ViewBag.Title = "Category";
}

<h2>Category</h2>

@using (Html.BeginForm("Create", "Supervisor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">*@
        @*@Html.LabelFor(model => model.cats.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })*@
        @*<div class="col-md-10">*@
        @*@Html.EditorFor(model => model.cats.CategoryId, new { htmlAttributes = new { @class = "form-control" } })*@
        @*@Html.ValidationMessageFor(model => model.cats.CategoryId, "", new { @class = "text-danger" })*@
        @*Category
                    @Html.DropDownListFor(model => model.cats.CategoryId, new SelectList(Model.cats.CategorySelectListItem, "Value", "Text"),
                new { @class = "form-control" })
                </div>
            </div>*@


        @*<div class="form-group">
                @Html.LabelFor(m => m.cats.CategoryId)
                @Html.DropDownListFor(m => m.cats.CategoryId, Model.cats.CategorySelectListItem, "-Please select-")
                @Html.ValidationMessageFor(m => m.cats.CategoryId)
            </div>*@


        @*<div class="item form-group">
                <div class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                    <span class="required">Role Name</span>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" name="CategoryName" id="CategoryName">
                        <option value="">Select Role</option>
                        @for (int i = 0; i < Model.pros.GetCategory.Tables[0].Rows.Count; i++)
                        {
                            var CategoryID = Model.pros.GetCategory.Tables[0].Rows[i]["CategoryId"].ToString();
                            var CategoryName = Model.pros.GetCategory.Tables[0].Rows[i]["CategoryName"].ToString();

                            <option value="@CategoryID">@CategoryName</option>
                        }
                    </select>
                    <span id="errRoleName"></span>
                </div>
            </div>*@





        <div class="form-group">
            <div class="col-md-5">
                <span class="glyphicon-asterisk" style="color:red;"></span>
                @Html.LabelFor(model => model.cats.CategoryName, htmlAttributes: new { @class = "control-label", style = "margin-bottom:10px;" })

                <label class="control-label col-md-10">Category</label>
                @Html.DropDownListFor(model => model.cats.CategoryName, (SelectList)ViewBag.AppDataApplicationType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cats.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>







        @*<div class="item form-group">
                <div class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                    <span class="required">Category Name</span>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" name="CategoryName" id="CategoryName">
                        <option value="">Select Role</option>
                        @for (int i = 0; i < Model.GetCategory.Tables[0].Rows.Count; i++)
                        {
                            var CategoryId = Model.GetCategory.Tables[0].Rows[i]["CategoryId"].ToString();
                            var CategoryName = Model.GetCategory.Tables[0].Rows[i]["CategoryName"].ToString();

                            <option value="@CategoryId">@CategoryName</option>
                        }
                    </select>
                    <span id="errRoleName"></span>
                </div>
            </div>*@


        <div class="form-group">
            @Html.LabelFor(model => model.pros.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pros.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pros.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pros.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pros.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pros.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pros.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" required="required" name="file" id="file" />
                @Html.ValidationMessageFor(model => model.pros.ProductImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pros.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pros.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pros.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Assignments/Views/Supervisor/Create.cshtml
@model  Assignments.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h3 class="text-success">@ViewBag.msg</h3>
@using (Html.BeginForm("Create", "Supervisor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" name="CategoryName" id="CategoryName">
                    <option value="">Select Category</option>
                    @for (int i = 0; i < Model.GetCategory.Tables[0].Rows.Count; i++)
                    {
                        var CategoryID = Model.GetCategory.Tables[0].Rows[i]["CategoryId"].ToString();
                        var CategoryName = Model.GetCategory.Tables[0].Rows[i]["CategoryName"].ToString();

                        <option value="@CategoryID">@CategoryName</option>
                    }
                </select>
                <span id="errRoleName"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" required="required" name="file" id="file" multiple />
                @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="visibility:hidden">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Assignments/Views/Supervisor/Edit.cshtml
@model Assignments.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<h3 class="text-danger">@ViewBag.msg</h3>
@using (Html.BeginForm("Edit", "Supervisor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryName, (IEnumerable<SelectListItem>)ViewBag.catlist,
                              new { @class = "form-control input-sm", @required = "required" })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Session["imgPath"].ToString())" height="70" width="100" />
                <input type="file" id="file" name="file" />
                @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group" style="visibility:hidden">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Assignments/Views/Supervisor/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@*@model IEnumerable<Assignments.Models.Product>*@
@model IPagedList<Assignments.Models.Product>


@{
    ViewBag.Title = "Index";
}

<h2>Product Details</h2>


@using (Html.BeginForm())
{
    <p>
        Search :
        <input type="text" name="keyword" required value="@ViewBag.Keyword" />
        <input type="submit" value="Search" />
        @*@Html.ActionLink("Create New","Create")*@
    </p>
}

@*@Session["username"].ToString();*@
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @Html.ActionLink("Upload From Excel", "Index", "UploadFromExcel")
</p>
<h4 class="text-success">
    @TempData["msg"]
</h4>


<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>*@
        @*<th>*@
        @*@Html.DisplayNameFor(model => model.ProductName)*@
        @*Product Name
            </th>
            <th>*@
        @*@Html.DisplayNameFor(model => model.Description)*@
        @*Description
            </th>*@
        <th>
            @Html.ActionLink("Product Name", "Index", new
           {
               sortOn= "ProductName",
               orderBy = ViewBag.OrderBy,
               pSortOn = ViewBag.SortOn,
               keyword = ViewBag.Keyword
           })
        </th>
        <th>
            @Html.ActionLink("Description", "Index", new
           {
               sortOn = "Description",
               orderBy = ViewBag.OrderBy,
               pSortOn = ViewBag.SortOn,
               keyword = ViewBag.Keyword
           })
        </th>

        <th>
            @*@Html.DisplayNameFor(model => model.ProductImage)*@
            Product Image
        </th>
        @*<th>*@
        @*@Html.DisplayNameFor(model => model.ProductPrice)*@
        @*Product Price*@
        @*</th>*@
        <th>
            @Html.ActionLink("Product Price", "Index", new
           {
               sortOn = "ProductPrice",
               orderBy = ViewBag.OrderBy,
               pSortOn = ViewBag.SortOn,
               keyword = ViewBag.Keyword
           })
        </th>
        <th colspan="2">
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.CategoryId)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="@Url.Content(item.ProductImage)" width="80" height="80" class="img-rounded" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ProductId })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.ProductId })
            </td>
        </tr>
    }

</table>
@*<div class="pagedList">
    @Html.PagedListPager(Model, page => Url.Action("Paging", new { page }),
    PagedListRenderOptions.PageNumbersOnly)
        </div>*@

<div class="pagedList">
    @Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    sortOn = ViewBag.SortOn,
    orderBy = ViewBag.OrderBy,
    pSortOn =
    ViewBag.SortOn,
    keyword = ViewBag.Keyword
}),
PagedListRenderOptions.ClassicPlusFirstAndLast)
</div>